# Generated by Django 3.2.4 on 2021-06-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movie_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='api/images/Noimg.jpg', upload_to='api/images'),
        ),
    ]
